version = 0.1
[default.deploy.parameters]
stack_name = "serverless-containers"
resolve_s3 = true
s3_prefix = "serverless-containers"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
disable_rollback = false
